import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Head from 'next/head';
import Header from '../components/Header';
import Footer from '../components/Footer'


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-custom-bg`}>
        <div>
          <header>
            <Header />
          </header>

          <main className="flex-grow">

          </main>

          <footer>
            <Footer />
          </footer>
        </div>
        {children}
      </body>
    </html>
  );
}
